### ISSUE TITLE
ERR_STREAM_PUSH_AFTER_EOF

### ISSUE THREAD

**Issue by two7sclash-zz** [lacymorrow/xspf-playlist#3]
`npx xspf-playlist '2018' '{"id3": false}' > playlist.xspf` 

results in the following:

```
Error [ERR_STREAM_PUSH_AFTER_EOF]: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:252:30)
    at Xspf.Readable.push (_stream_readable.js:219:10)
    at Xspf.Transform.push (_stream_transform.js:151:32)
    at Object.keys.filter.forEach.key (/Users/jamesfishwick/Documents/hbbj/node_modules/xspf-playlist/index.js:201:10)
    at Array.forEach (<anonymous>)
    at Xspf._transform (/Users/jamesfishwick/Documents/hbbj/node_modules/xspf-playlist/index.js:197:5)
    at Xspf.Transform._read (_stream_transform.js:190:10)
    at Xspf.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
zsh: exit 1     npx xspf-playlist '2018' '{"id3": false}' > playlist.xspf
```

npm version 6.1.0
node version v10.6.0

**Comment by lacymorrow** [comment]
looking into this...

**Comment by lacymorrow** [comment]
@two7sclash I have no issues using `npx` to run `xspf-jukebox`, but maybe you could try installing globally.

I have a feeling there are some corrupt input files, would it be possible to try on a folder of a single input file, and if you still get the error post the file?

**Comment by lacymorrow** [comment]
Closing due to no response.
